<a href="https://colab.research.google.com/github/Ch-varshitha/Scikit-Learn/blob/main/Copy_of_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import sklearn

In [ ]:
from sklearn.datasets import make_regression

In [ ]:
make_regression(n_samples=20, n_features=4)

(array([[-1.6753604 , -2.46787713, -0.03289318, -0.64802652],
        [-1.4595534 , -0.613276  ,  0.48678074,  0.18426791],
        [-0.04287123, -0.27166388,  1.22726543,  1.16402614],
        [-0.291451  , -0.53312973,  0.32591819,  0.75386882],
        [-1.27194942, -1.35881175, -0.30913586, -1.30600669],
        [ 0.28264872, -0.04468851, -2.52080924, -0.18296378],
        [-0.87813594,  0.78865639, -2.17888128, -0.44277038],
        [-1.20229501, -0.29366803, -0.70604767,  1.56169687],
        [ 1.27258802,  0.58888848,  0.54909751,  0.67996545],
        [ 0.20668115,  0.90189923,  0.2144665 , -2.08925862],
        [ 1.19529463,  0.54433604,  0.45477535, -0.55937789],
        [-0.78416138, -0.81314436,  0.39420116, -1.13485876],
        [ 0.18058289,  1.29896933,  1.71080244,  1.67371572],
        [-1.4863016 ,  0.78052252, -0.95041451,  0.22840332],
        [ 1.04012884,  0.26566649, -0.3992959 ,  1.51688304],
        [ 1.67614692,  1.56271264,  0.25700017, -0.96207994],
        [ 0.43418398, -1.67510821,  0.07330454, -0.38219202],
        [ 0.93464569, -0.60861402, -0.13460079,  0.03395752],
        [ 0.02203248,  0.32705073, -0.5009129 ,  0.16862487],
        [-0.00410322,  1.62123955,  0.21526962,  1.98160728]]),
 array([-328.32725377, -115.02389446,  123.69634433,    3.03753451,
        -277.4298022 , -165.49578729, -196.87527351,  -88.16962869,
         214.12192469,  -15.77885641,  136.16461259, -145.05057312,
         300.92133423, -127.43991941,  150.16023561,  205.97112331,
         -84.56123816,   30.28252039,   -4.12115936,  216.86204505]))

In [ ]:
x,y = make_regression(n_samples=20, n_features=4, bias=10.3, noise=1.8)

In [ ]:
x.shape

(20, 4)

In [ ]:
y.shape

(20,)

In [ ]:
df = pd.DataFrame(x).round(2)

In [ ]:
df

       0     1     2     3
0   1.51 -1.46  0.10  0.91
1  -0.14 -1.27  0.84  0.90
2  -0.42 -3.16  3.29 -0.29
3  -1.03  0.04  0.77  0.49
4  -1.34 -0.07  0.39 -2.34
5   0.18 -1.11 -0.24  0.80
6   1.21  0.66  1.70 -0.04
7  -0.49  1.24  0.97 -0.28
8  -1.41 -0.80 -0.73  0.90
9  -1.14  0.40 -1.67 -0.28
10 -0.44 -0.88 -1.35  0.08
11  0.85 -0.59 -0.61 -0.60
12  0.02 -0.16 -0.01  0.87
13  1.48 -1.40  1.36  0.44
14  0.48 -2.10  0.45  1.46
15 -1.07  0.34  2.84  0.02
16 -0.40  0.88 -1.76 -0.62
17  0.69 -0.79 -0.96  0.53
18  0.42  1.04  1.08 -0.93
19 -0.14  0.44 -0.94 -0.62

In [ ]:
df.columns = ["col1","col2","col3","col4"]

In [ ]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"bangalore",
    "col4":"hyderabad"
},inplace=True)

In [ ]:
df

    delhi  mumbai  bangalore  hyderabad
0    1.51   -1.46       0.10       0.91
1   -0.14   -1.27       0.84       0.90
2   -0.42   -3.16       3.29      -0.29
3   -1.03    0.04       0.77       0.49
4   -1.34   -0.07       0.39      -2.34
5    0.18   -1.11      -0.24       0.80
6    1.21    0.66       1.70      -0.04
7   -0.49    1.24       0.97      -0.28
8   -1.41   -0.80      -0.73       0.90
9   -1.14    0.40      -1.67      -0.28
10  -0.44   -0.88      -1.35       0.08
11   0.85   -0.59      -0.61      -0.60
12   0.02   -0.16      -0.01       0.87
13   1.48   -1.40       1.36       0.44
14   0.48   -2.10       0.45       1.46
15  -1.07    0.34       2.84       0.02
16  -0.40    0.88      -1.76      -0.62
17   0.69   -0.79      -0.96       0.53
18   0.42    1.04       1.08      -0.93
19  -0.14    0.44      -0.94      -0.62

In [ ]:
pd.date_range("04-07-20",periods=10,freq="m")

/tmp/ipykernel_946/3983751442.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range("04-07-20",periods=10,freq="m")

DatetimeIndex(['2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31',
               '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30',
               '2020-12-31', '2021-01-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
df.set_index(pd.date_range("04-07-20",periods=20,freq="D"),inplace=True)

In [ ]:
df

            delhi  mumbai  bangalore  hyderabad
2020-04-07   1.51   -1.46       0.10       0.91
2020-04-08  -0.14   -1.27       0.84       0.90
2020-04-09  -0.42   -3.16       3.29      -0.29
2020-04-10  -1.03    0.04       0.77       0.49
2020-04-11  -1.34   -0.07       0.39      -2.34
2020-04-12   0.18   -1.11      -0.24       0.80
2020-04-13   1.21    0.66       1.70      -0.04
2020-04-14  -0.49    1.24       0.97      -0.28
2020-04-15  -1.41   -0.80      -0.73       0.90
2020-04-16  -1.14    0.40      -1.67      -0.28
2020-04-17  -0.44   -0.88      -1.35       0.08
2020-04-18   0.85   -0.59      -0.61      -0.60
2020-04-19   0.02   -0.16      -0.01       0.87
2020-04-20   1.48   -1.40       1.36       0.44
2020-04-21   0.48   -2.10       0.45       1.46
2020-04-22  -1.07    0.34       2.84       0.02
2020-04-23  -0.40    0.88      -1.76      -0.62
2020-04-24   0.69   -0.79      -0.96       0.53
2020-04-25   0.42    1.04       1.08      -0.93
2020-04-26  -0.14    0.44      -0.94      -0.62

In [ ]:
df.to_excel("regression.xlsx")

In [ ]:
pd.read_excel("regression2.xlsx")

   Unnamed: 0  delhi  mumbai  bangalore  hyderabad
0  2020-04-07   1.51   -1.46       0.10       0.91
1  2020-04-08  -0.14   -1.27       0.84       0.90
2  2020-04-09  -0.42   -3.16       3.29      -0.29
3  2020-04-10  -1.03    0.04       0.77       0.49
4  2020-04-11  -1.34   -0.07       0.39      -2.34
5  2020-04-12   0.18   -1.11      -0.24       0.80
6  2020-04-13   1.21    0.66       1.70      -0.04
7  2020-04-14  -0.49    1.24       0.97      -0.28
8  2020-04-15  -1.41   -0.80      -0.73       0.90
9  2020-04-16  -1.14    0.40      -1.67      -0.28
10 2020-04-17  -0.44   -0.88      -1.35       0.08
11 2020-04-18   0.85   -0.59      -0.61      -0.60
12 2020-04-19   0.02   -0.16      -0.01       0.87
13 2020-04-20   1.48   -1.40       1.36       0.44
14 2020-04-21   0.48   -2.10       0.45       1.46
15 2020-04-22  -1.07    0.34       2.84       0.02
16 2020-04-23  -0.40    0.88      -1.76      -0.62
17 2020-04-24   0.69   -0.79      -0.96       0.53
18 2020-04-25   0.42    1.04       1.08      -0.93
19 2020-04-26  -0.14    0.44      -0.94      -0.62

In [ ]:
ndf = pd.read_excel("regression2.xlsx",index_col="Unnamed: 0")

In [ ]:
ndf

            delhi  mumbai  bangalore  hyderabad
2020-04-07   1.51   -1.46       0.10       0.91
2020-04-08  -0.14   -1.27       0.84       0.90
2020-04-09  -0.42   -3.16       3.29      -0.29
2020-04-10  -1.03    0.04       0.77       0.49
2020-04-11  -1.34   -0.07       0.39      -2.34
2020-04-12   0.18   -1.11      -0.24       0.80
2020-04-13   1.21    0.66       1.70      -0.04
2020-04-14  -0.49    1.24       0.97      -0.28
2020-04-15  -1.41   -0.80      -0.73       0.90
2020-04-16  -1.14    0.40      -1.67      -0.28
2020-04-17  -0.44   -0.88      -1.35       0.08
2020-04-18   0.85   -0.59      -0.61      -0.60
2020-04-19   0.02   -0.16      -0.01       0.87
2020-04-20   1.48   -1.40       1.36       0.44
2020-04-21   0.48   -2.10       0.45       1.46
2020-04-22  -1.07    0.34       2.84       0.02
2020-04-23  -0.40    0.88      -1.76      -0.62
2020-04-24   0.69   -0.79      -0.96       0.53
2020-04-25   0.42    1.04       1.08      -0.93
2020-04-26  -0.14    0.44      -0.94      -0.62

In [ ]:
ndf.loc[:,"delhi"]

2020-04-07    1.51
2020-04-08   -0.14
2020-04-09   -0.42
2020-04-10   -1.03
2020-04-11   -1.34
2020-04-12    0.18
2020-04-13    1.21
2020-04-14   -0.49
2020-04-15   -1.41
2020-04-16   -1.14
2020-04-17   -0.44
2020-04-18    0.85
2020-04-19    0.02
2020-04-20    1.48
2020-04-21    0.48
2020-04-22   -1.07
2020-04-23   -0.40
2020-04-24    0.69
2020-04-25    0.42
2020-04-26   -0.14
Name: delhi, dtype: float64

In [ ]:
ndf[ndf["delhi"]>0]

            delhi  mumbai  bangalore  hyderabad
2020-04-07   1.51   -1.46       0.10       0.91
2020-04-12   0.18   -1.11      -0.24       0.80
2020-04-13   1.21    0.66       1.70      -0.04
2020-04-18   0.85   -0.59      -0.61      -0.60
2020-04-19   0.02   -0.16      -0.01       0.87
2020-04-20   1.48   -1.40       1.36       0.44
2020-04-21   0.48   -2.10       0.45       1.46
2020-04-24   0.69   -0.79      -0.96       0.53
2020-04-25   0.42    1.04       1.08      -0.93

In [ ]:
ndf[(ndf["delhi"] > 0) & (ndf["mumbai"] > 0)]

            delhi  mumbai  bangalore  hyderabad
2020-04-13   1.21    0.66       1.70      -0.04
2020-04-25   0.42    1.04       1.08      -0.93