<a href="https://colab.research.google.com/github/Ch-varshitha/Scikit-Learn/blob/main/Scikit_learn_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.datasets import make_regression,load_iris

In [2]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
dt=load_iris()

In [4]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
df=pd.DataFrame(dt.data,columns=dt.feature_names)

In [14]:
df.rename(columns={'sepal length (cm)':'sepal_length', 'sepal width (cm)':'sepal_width', 'petal length (cm)':'petal_length', 'petal width (cm)':'petal_width'}, inplace=True)

In [15]:
df[df['sepal_length']>5]

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
5             5.4          3.9           1.7          0.4       0
10            5.4          3.7           1.5          0.2       0
14            5.8          4.0           1.2          0.2       0
15            5.7          4.4           1.5          0.4       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[118 rows x 5 columns]

In [11]:
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [12]:
df['target'] = dt.target

In [13]:
df

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [20]:
df.loc[df['sepal_length']<6,'new_column']='small sepals'

In [21]:
df.loc[df['sepal_length']>=6,'new_column']='big sepals'

In [23]:
df['updated_column']=df['sepal_length'].apply(lambda x: 'small sepals' if x<6 else 'large sepals')

In [24]:
df

,sepal_length,sepal_width,petal_length,petal_width,target,new_column,updated_column
0,5.1,3.5,1.4,0.2,0,small sepals,small sepals
1,4.9,3.0,1.4,0.2,0,small sepals,small sepals
2,4.7,3.2,1.3,0.2,0,small sepals,small sepals
3,4.6,3.1,1.5,0.2,0,small sepals,small sepals
4,5.0,3.6,1.4,0.2,0,small sepals,small sepals
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,big sepals,large sepals
146,6.3,2.5,5.0,1.9,2,big sepals,large sepals
147,6.5,3.0,5.2,2.0,2,big sepals,large sepals
148,6.2,3.4,5.4,2.3,2,big sepals,large sepals
149,5.9,3.0,5.1,1.8,2,small sepals,small sepals

,sepal_length,sepal_width,petal_length,petal_width,target,new_column
0,5.1,3.5,1.4,0.2,0,small sepals
1,4.9,3.0,1.4,0.2,0,small sepals
2,4.7,3.2,1.3,0.2,0,small sepals
3,4.6,3.1,1.5,0.2,0,small sepals
4,5.0,3.6,1.4,0.2,0,small sepals
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,NaN
146,6.3,2.5,5.0,1.9,2,NaN
147,6.5,3.0,5.2,2.0,2,NaN
148,6.2,3.4,5.4,2.3,2,NaN
149,5.9,3.0,5.1,1.8,2,small sepals

In [ ]:
x,y=make_regression(n_samples=20,n_features=4,bias=10.3,noise=1.8)

In [ ]:
x.shape

(20, 4)

In [ ]:
y.shape

(20,)

In [ ]:
df=pd.DataFrame(x).round(2)

In [ ]:
df

       0     1     2     3
0   0.00 -0.17 -0.87 -0.04
1  -0.71  0.21 -0.46  0.20
2   0.22 -0.90 -1.06  0.93
3   0.50 -0.64  0.61  0.91
4   1.21 -0.07  0.44 -1.03
5   0.52  0.46  2.64 -0.41
6   0.07 -1.15 -1.19 -1.61
7   1.30  0.72  0.28 -0.75
8   0.45 -1.83 -1.29  0.02
9  -0.56  0.41 -0.58 -0.39
10 -0.72  0.10 -0.87  0.68
11 -0.24 -0.42 -1.90 -2.34
12  2.57  0.72  0.39  2.15
13  1.70  0.04  0.56 -0.48
14  0.99  0.75  0.33 -1.15
15  0.11 -1.04  0.11  0.97
16 -1.32  0.66  0.45  1.70
17  0.30 -0.31  0.68 -0.39
18  1.37 -0.06 -0.42  1.36
19 -0.62  0.78 -0.48 -0.76

In [ ]:
df.columns = ["col1","col2","col3","col4"]

In [ ]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"bangalore",
    "col4":"hyderabad"
},inplace=True)

In [ ]:
df

    delhi  mumbai  bangalore  hyderabad
0    0.00   -0.17      -0.87      -0.04
1   -0.71    0.21      -0.46       0.20
2    0.22   -0.90      -1.06       0.93
3    0.50   -0.64       0.61       0.91
4    1.21   -0.07       0.44      -1.03
5    0.52    0.46       2.64      -0.41
6    0.07   -1.15      -1.19      -1.61
7    1.30    0.72       0.28      -0.75
8    0.45   -1.83      -1.29       0.02
9   -0.56    0.41      -0.58      -0.39
10  -0.72    0.10      -0.87       0.68
11  -0.24   -0.42      -1.90      -2.34
12   2.57    0.72       0.39       2.15
13   1.70    0.04       0.56      -0.48
14   0.99    0.75       0.33      -1.15
15   0.11   -1.04       0.11       0.97
16  -1.32    0.66       0.45       1.70
17   0.30   -0.31       0.68      -0.39
18   1.37   -0.06      -0.42       1.36
19  -0.62    0.78      -0.48      -0.76

In [ ]:
pd.date_range("04-07-20",periods=10,freq="m")

/tmp/ipykernel_1355/3983751442.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range("04-07-20",periods=10,freq="m")

DatetimeIndex(['2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31',
               '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30',
               '2020-12-31', '2021-01-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
df.set_index(pd.date_range("04-07-20",periods=20,freq="D"),inplace=True)

In [ ]:
df

            delhi  mumbai  bangalore  hyderabad
2020-04-07   0.00   -0.17      -0.87      -0.04
2020-04-08  -0.71    0.21      -0.46       0.20
2020-04-09   0.22   -0.90      -1.06       0.93
2020-04-10   0.50   -0.64       0.61       0.91
2020-04-11   1.21   -0.07       0.44      -1.03
2020-04-12   0.52    0.46       2.64      -0.41
2020-04-13   0.07   -1.15      -1.19      -1.61
2020-04-14   1.30    0.72       0.28      -0.75
2020-04-15   0.45   -1.83      -1.29       0.02
2020-04-16  -0.56    0.41      -0.58      -0.39
2020-04-17  -0.72    0.10      -0.87       0.68
2020-04-18  -0.24   -0.42      -1.90      -2.34
2020-04-19   2.57    0.72       0.39       2.15
2020-04-20   1.70    0.04       0.56      -0.48
2020-04-21   0.99    0.75       0.33      -1.15
2020-04-22   0.11   -1.04       0.11       0.97
2020-04-23  -1.32    0.66       0.45       1.70
2020-04-24   0.30   -0.31       0.68      -0.39
2020-04-25   1.37   -0.06      -0.42       1.36
2020-04-26  -0.62    0.78      -0.48      -0.76

In [ ]:
df.to_excel("regression.xlsx")

In [ ]:
pd.read_excel("regression2.xlsx")

   Unnamed: 0  delhi  mumbai  bangalore  hyderabad
0  2020-04-07   0.00   -0.17      -0.87      -0.04
1  2020-04-08  -0.71    0.21      -0.46       0.20
2  2020-04-09   0.22   -0.90      -1.06       0.93
3  2020-04-10   0.50   -0.64       0.61       0.91
4  2020-04-11   1.21   -0.07       0.44      -1.03
5  2020-04-12   0.52    0.46       2.64      -0.41
6  2020-04-13   0.07   -1.15      -1.19      -1.61
7  2020-04-14   1.30    0.72       0.28      -0.75
8  2020-04-15   0.45   -1.83      -1.29       0.02
9  2020-04-16  -0.56    0.41      -0.58      -0.39
10 2020-04-17  -0.72    0.10      -0.87       0.68
11 2020-04-18  -0.24   -0.42      -1.90      -2.34
12 2020-04-19   2.57    0.72       0.39       2.15
13 2020-04-20   1.70    0.04       0.56      -0.48
14 2020-04-21   0.99    0.75       0.33      -1.15
15 2020-04-22   0.11   -1.04       0.11       0.97
16 2020-04-23  -1.32    0.66       0.45       1.70
17 2020-04-24   0.30   -0.31       0.68      -0.39
18 2020-04-25   1.37   -0.06      -0.42       1.36
19 2020-04-26  -0.62    0.78      -0.48      -0.76

In [ ]:
ndf = pd.read_excel("regression2.xlsx",index_col="Unnamed: 0")

In [ ]:
ndf

            delhi  mumbai  bangalore  hyderabad
2020-04-07   0.00   -0.17      -0.87      -0.04
2020-04-08  -0.71    0.21      -0.46       0.20
2020-04-09   0.22   -0.90      -1.06       0.93
2020-04-10   0.50   -0.64       0.61       0.91
2020-04-11   1.21   -0.07       0.44      -1.03
2020-04-12   0.52    0.46       2.64      -0.41
2020-04-13   0.07   -1.15      -1.19      -1.61
2020-04-14   1.30    0.72       0.28      -0.75
2020-04-15   0.45   -1.83      -1.29       0.02
2020-04-16  -0.56    0.41      -0.58      -0.39
2020-04-17  -0.72    0.10      -0.87       0.68
2020-04-18  -0.24   -0.42      -1.90      -2.34
2020-04-19   2.57    0.72       0.39       2.15
2020-04-20   1.70    0.04       0.56      -0.48
2020-04-21   0.99    0.75       0.33      -1.15
2020-04-22   0.11   -1.04       0.11       0.97
2020-04-23  -1.32    0.66       0.45       1.70
2020-04-24   0.30   -0.31       0.68      -0.39
2020-04-25   1.37   -0.06      -0.42       1.36
2020-04-26  -0.62    0.78      -0.48      -0.76

In [ ]:
ndf.loc[:,"delhi"]

2020-04-07    0.00
2020-04-08   -0.71
2020-04-09    0.22
2020-04-10    0.50
2020-04-11    1.21
2020-04-12    0.52
2020-04-13    0.07
2020-04-14    1.30
2020-04-15    0.45
2020-04-16   -0.56
2020-04-17   -0.72
2020-04-18   -0.24
2020-04-19    2.57
2020-04-20    1.70
2020-04-21    0.99
2020-04-22    0.11
2020-04-23   -1.32
2020-04-24    0.30
2020-04-25    1.37
2020-04-26   -0.62
Name: delhi, dtype: float64

In [ ]:
ndf[ndf["delhi"]>0]

            delhi  mumbai  bangalore  hyderabad
2020-04-09   0.22   -0.90      -1.06       0.93
2020-04-10   0.50   -0.64       0.61       0.91
2020-04-11   1.21   -0.07       0.44      -1.03
2020-04-12   0.52    0.46       2.64      -0.41
2020-04-13   0.07   -1.15      -1.19      -1.61
2020-04-14   1.30    0.72       0.28      -0.75
2020-04-15   0.45   -1.83      -1.29       0.02
2020-04-19   2.57    0.72       0.39       2.15
2020-04-20   1.70    0.04       0.56      -0.48
2020-04-21   0.99    0.75       0.33      -1.15
2020-04-22   0.11   -1.04       0.11       0.97
2020-04-24   0.30   -0.31       0.68      -0.39
2020-04-25   1.37   -0.06      -0.42       1.36

In [ ]:
ndf[(ndf["delhi"] > 0) & (ndf["mumbai"] > 0)]

            delhi  mumbai  bangalore  hyderabad
2020-04-12   0.52    0.46       2.64      -0.41
2020-04-14   1.30    0.72       0.28      -0.75
2020-04-19   2.57    0.72       0.39       2.15
2020-04-20   1.70    0.04       0.56      -0.48
2020-04-21   0.99    0.75       0.33      -1.15